name: build python

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - python/**

permissions:
  actions: read
  packages: write

concurrency:
  group: python-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.7
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - "3.10" # !WARNING: Tag must be enclosed in quotes or it will be interpreted as 3.1 instead of 3.10
          - 3.11
          - 3.12
          - 3.13-rc
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./python
          platforms: linux/amd64,linux/arm64
          file: ./python/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/software-noob/pterodactyl-images:python_${{ matrix.tag }}
